#!/bin/bash
#PBS -S /bin/bash
#PBS -N Au_H_NA
#PBS -l gpus=1:default,walltime=48:00:00
#PBS -q p100_normal_q
#PBS -M wangsh@vt.edu
#PBS -W group_list=newriver
#PBS -m ae
#PBS -o std.o
#PBS -e std.e
#PBS -V
#PBS -A force_field

module purge

module load Anaconda

source activate Python_3.6_TensorFlow_PyTorch_GPU

module load gcc cmake
module load cuda/8.0.44
module load cudnn/6.0

cd $PBS_O_WORKDIR
export MACHINE_COUNT=24

python Figure.py
