#!/bin/bash
#SBATCH -t 48:00:00
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --mem=300G
#SBATCH --ntasks-per-node 24
#SBATCH -p v100_normal_q
#SBATCH -A casc_xinlab
#SBATCH --job-name="5.5"
#SBATCH --output=std.out
#SBATCH --mail-user=hxin@vt.edu
#SBATCH --mail-type=ALL

module purge

module load Anaconda
module load pytorch/5.4.4-arc
module load gcc cmake
module load cuda/9.2.148
module load cudnn/7.1

cd $SLURM_SUBMIT_DIR
export MACHINE_COUNT=$SLURM_NTASKS

./Script.py
